# Generated by Django 2.2.15 on 2020-11-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('format_', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atribut',
        ),
        migrations.DeleteModel(
            name='Entitet',
        ),
    ]
